#!/usr/bin/bash
#for i3config
if [ -z ${brt+x} ] || [[ $brt -ne "-1" ]]; then
	brt=$(xbacklight -get)
	echo $brt
fi

xbacklight -set 0
${1:-i3lock -n -i /home/flash/Pictures/Wallpapers/arch_simple1080.png -u -b}
xbacklight -set $brt

brt=-1
