#!/usr/bin/bash
#for i3config
if [[ $brt -ne "-1" ]] || [ -z ${brt+x} ]; then
	brt=$(xbacklight -get)
	echo $brt
fi

: ${1?"Pass a lock command. Thank you!"}

xbacklight -set 0
$1
xbacklight -set $brt

brt=-1
